### PR TITLE
Create Release WorkFlow Git Action

### PR DESCRIPTION
**Pull request by waterfallm**
Use GitActions to produce Release and give confidence img file comes from source

## Description
Simple Git Action takes 2 hrs to run for each build.
Manually triggered by click on Run Workflow in Git Actions TAB

image

## How Has This Been Tested?
Has been run on my own fork(https://github.com/waterfallm/) and i'll run a few more tests before submitting proper.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by aluminum-ice** [comment]
I like this PR. Would love to try it once it's ready.

**Comment by waterfallm** [comment]
> I like this PR. Would love to try it once it's ready.

Will sort ASAP.

**Comment by aluminum-ice** [comment]
There is a catch you need to consider. Since I compile nexmon in the build process, the image is huge with lots of empty space at the end. So, I run pishrink on it manually to shrink it. How will you recreate that in the gitaction?

**Comment by waterfallm** [comment]
> There is a catch you need to consider. Since I compile nexmon in the build process, the image is huge with lots of empty space at the end. So, I run pishrink on it manually to shrink it. How will you recreate that in the gitaction?

Yeap currently working on 2 issues..

1. setting env.VERSION properly in action.
2. size being > 2Gb looks like your suggestion will resolve that.

image

**Comment by waterfallm** [comment]
@aluminum-ice 

Latest update seems to have trimmed off enough i will test image produced once I've finished work today

image

**Comment by waterfallm** [comment]
This test 1.7.9 version works straight from image produced using CreateRelease.

Only issue is git action file needs version manually updating at each run, no big issue for now.

image

**Comment by waterfallm** [comment]
https://github.com/waterfallm/pwnagotchi/releases/download/19/pwnagotchi-v1.7.9.7z

**Comment by aluminum-ice** [comment]
pishrink will change the sha256 value. The action needs to run sha256sum to compute the right value for the shrunk image. Example:

`sha256sum pwnagotchi-raspios-lite-1.7.9-shrink.img >  pwnagotchi-raspios-lite-1.7.9-shrink.sha256`

**Comment by waterfallm** [comment]
> pishrink will change the sha256 value. The action needs to run sha256sum to compute the right value for the shrunk image. Example:
> 
> `sha256sum pwnagotchi-raspios-lite-1.7.9-shrink.img > pwnagotchi-raspios-lite-1.7.9-shrink.sha256`

Command to update sha and label of release changed to version number

**Review by aluminum-ice — APPROVED** [review]

**Comment by aluminum-ice** [comment]
Thank you for your contribution. I just merged and I am running the action now to create release 1.8.0

**Pull request merged**
