### PR TITLE
add support for the v2 variant of the waveshare 2.7 inch display

### PR DESCRIPTION
**Pull request by brianhealey**
Adds support for the V2 variant of the waveshare 2.7 inch display. This display uses a different library from the V1 display.

## Description
Includes updated display settings for the new display type.  All added files were taken from the source at https://github.com/waveshareteam/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in7_V2.py

## Motivation and Context
The current code base supports v1 hardware which wasn't available on amazon. 

- [X] I have raised an issue to propose this change ([required](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Deployed a full 1.7.8 deployment from SD card. Fixed issues that were preventing RPI4 to work in monitoring mode. Manually updated these files.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/evilsocket/pwnagotchi/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by aluminum-ice** [comment]
I don't follow why this line of code:

`def is_waveshare27inch(self):`
`        return self._implementation.name == 'waveshare27inch' or self._implementation.name == 'waveshare27inchv2'`

Why the or statement? This is an outlier compared to other definitions for other screens.

**Comment by brianhealey** [comment]
The plugins battery and gps use this check to position the text. If this is not changed they will appear different on v1 vs v2. I could not find any other usages of this method aside from visual positioning.

**Comment by aluminum-ice** [comment]
Have you tested this thoroughly with my latest commits to ensure there are no issues? I don't have this screen so I won't be able to test it. If you confirm you've tested it, I will merge it.

**Comment by ryanbeard82** [comment]
I tested with the bettercap.py updates from a couple of days ago, but haven't checked for anything more recent. I'll pull and test again.

**Comment by brianhealey** [comment]
I can pull and test again tomorrow if you haven't already.

**Pull request merged**
